version: "3.1"

services:
  mysql:
    container_name: myimouto_mysql
    image: mysql:5.6
    restart: always
    volumes:
      - /srv/myimouto/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: <put the mysql password here>
  myimouto:
    container_name: myimouto
    image: chrll/myimouto:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - 3000:3000
    volumes:
      - /srv/myimouto/data:/srv/myimouto/public/data
      - /srv/myimouto/config:/config
    environment:
      MYSQL_SERVER: mysql
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: <put the mysql password here>
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: <put the myimouto admin password here>
      TZ: UTC
      SERVER_HOST: 127.0.0.1:3000
      URL_BASE: http://127.0.0.1:3000/
